AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ec2-instance with splunk enterprise server 

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC where you want to deploy your EC2 instance
    AllowedPattern : ".+"
  Environment:
    Type: String
    Description: Environment name
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
    ConstraintDescription: must specify dev, qa or prod.
  SplunkInstallerUrl:
    Type: String
    Description: Splunk installer URL
    AllowedPattern : ".+"


Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-080e1f13689e07408 
    us-east-2:
      AMI: ami-0b8b44ec9a8f90422
    us-west-1:
      AMI: ami-05c969369880fa2c2 
    us-west-2:
      AMI:  ami-08116b9957a259459

Resources:

  EC2SplunkRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${Environment}-splunk-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Tags:
        - Key: Group 
          Value: !Sub "${AWS::StackName}"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      Policies:
        - PolicyName: !Sub "${Environment}-splunk-policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "cloudwatch:ListMetrics"
                  - "cloudwatch:ListDashboards"
                  - "cloudwatch:ListMetricStreams"
                  - "cloudwatch:ListServiceLevelObjectives"
                  - "cloudwatch:ListServices"
                  - "cloudwatch:ListTagsForResource"
                  - "cloudwatch:GetMetricStatistics"
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:GetLogEvents"
                  - "s3:GetBucketLocation"
                  - "ec2:DescribeInstances"
                  - "autoscaling:DescribeAutoScalingGroups"
                  - "autoscaling:DescribeLaunchConfigurations"
                Resource: "*"

  EC2SplunkProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: /
      Roles:
        - !Ref EC2SplunkRole
      InstanceProfileName: !Sub "${Environment}-splunk-instance-profile"

  EC2SplunkSecurityGroup:
    # DependsOn: ALBSecurityGroup
    Type: "AWS::EC2::SecurityGroup"
    Properties:
        GroupDescription: "security group for splunk"
        GroupName: !Sub "${Environment}-splunk-security-group" 
        Tags: 
          - Key: Group
            Value: !Sub "${AWS::StackName}"
        VpcId: !Ref VpcId
        SecurityGroupIngress: 
          - FromPort: 8000
            IpProtocol: 'tcp'
            ToPort: 8000 
            CidrIp: '0.0.0.0/0'
          - FromPort: 22
            IpProtocol: 'tcp'
            ToPort: 22
            CidrIp: '0.0.0.0/0'

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub "${Environment}-splunk-keypair"
      Tags:
        - Key: Group
          Value: !Sub "${AWS::StackName}"

  EC2Splunk:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: t2.large
      IamInstanceProfile: !Ref EC2SplunkProfile
      SecurityGroupIds:
        - !Ref EC2SplunkSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          echo "installing splunk"
          wget -O /tmp/splunk.deb ${SplunkInstallerUrl}
          dpkg -i /tmp/splunk.deb
          wget -O /opt/splunk/etc/system/local/user-seed.conf https://raw.githubusercontent.com/wladitrujillo/uide-aws-environment/main/assets/splunk/user-seed.conf 
          sudo /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
          sudo /opt/splunk/bin/splunk enable boot-start
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-splunk"
        - Key: Group
          Value: !Ref AWS::StackName


Outputs:

  EC2InstanceID:
    Description: The Instance ID of the newly created EC2 instance
    Value: !Ref EC2Splunk
    Export:
      Name: !Sub "${AWS::StackName}-EC2InstanceID"

  EC2PrivateIP:
    Description: The private IP address of the newly created EC2 instance
    Value: !GetAtt EC2Splunk.PrivateIp
    Export:
      Name: !Sub "${AWS::StackName}-EC2PrivateIP"

  EC2PublicIP:
    Description: The public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Splunk.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-EC2PublicIP"
